lib/smoke_web/router.ex
defmodule SmokeWeb.Router do
  use SmokeWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", SmokeWeb do
    pipe_through(:browser)
    get("/events/:event_name/:measurement/:metric_name/:precision", MetricsController, :metrics)
    get("/events/:event_name/:measurement/:metric_name", MetricsController, :list_precisions)
    get("/events/:event_name/:measurement", MetricsController, :list_metrics)
    get("/events/:event_name", MetricsController, :list_measurements)
    get("/", MetricsController, :list_events)
  end
end

lib/smoke/metrics.ex
defmodule Smoke.Metrics do
  @moduledoc """
  Creates Metrics from a list of events.
  """

  def filter(events, {tag, value}) do
    events
    |> Stream.filter(fn
      {_time, _measurement, metadata} ->
        Enum.any?(metadata, fn
          {^tag, ^value} -> true
          _ -> false
        end)
    end)
  end

  def filter(events, [head | tail]) do
    events
    |> filter(head)
    |> filter(tail)
  end

  def filter(events, []), do: events

  def time_bucket(events, precision) do
    Stream.chunk_by(events, fn {time, _measurement, _metadata} ->
      truncate(time, precision)
    end)
    |> Stream.map(fn [{time, _measurement, _metadata} | _tail] = events ->
      %{time: truncate(time, precision), events: events}
    end)
  end

  def truncate(date_time, :month), do: %{truncate(date_time, :day) | day: 1}
  def truncate(date_time, :day), do: %{truncate(date_time, :hour) | hour: 0}
  def truncate(date_time, :hour), do: %{truncate(date_time, :minute) | minute: 0}
  def truncate(date_time, :minute), do: %{truncate(date_time, :second) | second: 0}
  def truncate(date_time, precision), do: DateTime.truncate(date_time, precision)

  def tags(events) do
    events
    |> Enum.reduce(MapSet.new(), fn
      {_time, _measurement, metadata}, acc ->
        metadata |> Map.keys() |> Enum.into(acc)
    end)
    |> MapSet.to_list()
  end

  def apply_to_bucketed_events(bucketed_events, key, metrics_function) do
    Stream.map(bucketed_events, fn %{time: time, events: events} ->
      %{time: time, metric: metrics_function.(events, key)}
    end)
  end

  def measurements(events) do
    events
    |> Enum.reduce(MapSet.new(), fn
      {_time, measurement, _metadata}, acc ->
        measurement |> Map.keys() |> Enum.into(acc)
    end)
    |> MapSet.to_list()
  end

  def tag_values(events, tag_name) do
    events
    |> Enum.reduce(MapSet.new(), fn
      {_time, _measurement, metadata}, acc ->
        value = Map.get(metadata, tag_name)
        MapSet.put(acc, value)
    end)
    |> MapSet.to_list()
  end

  def counter(events, key) do
    get_measure = measurement_value(key)

    events
    |> Stream.map(get_measure)
    |> Enum.count(fn x -> not is_nil(x) end)
  end

  def sum(events, key) do
    get_measure = measurement_value(key, 0)

    events
    |> Stream.map(get_measure)
    |> Enum.sum()
  end

  def last_value([{_time, measurement, _metadata} = _head | tail], key) do
    if Map.has_key?(measurement, key) do
      Map.get(measurement, key)
    else
      last_value(tail, key)
    end
  end

  def last_value(_events, _key), do: nil

  def statistics(events, key) do
    get_measure = measurement_value(key)

    measurements =
      events
      |> Enum.map(get_measure)
      |> Enum.filter(fn measure -> not is_nil(measure) end)

    %{
      median: Statistics.median(measurements),
      mean: Statistics.mean(measurements),
      max: Statistics.max(measurements),
      min: Statistics.min(measurements),
      mode: Statistics.mode(measurements),
      variance: Statistics.variance(measurements),
      p95: Statistics.percentile(measurements, 95),
      p99: Statistics.percentile(measurements, 99)
    }
  end

  def distribution(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.hist()
  end

  def max(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.max()
  end

  def mean(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.mean()
  end

  def median(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.median()
  end

  def min(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.min()
  end

  def mode(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.mode()
  end

  def p95(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.percentile(95)
  end

  def p99(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.percentile(99)
  end

  def variance(events, key) do
    get_measure = measurement_value(key)

    events
    |> Enum.map(get_measure)
    |> Statistics.variance()
  end

  def first_event_time([]), do: nil

  def first_event_time(events) do
    events |> List.last() |> elem(0)
  end

  defp measurement_value(key, default \\ nil) do
    fn {_time, measurement, _metadata} ->
      Map.get(measurement, key, default)
    end
  end
end

lib/smoke_web/controllers/metrics_controller.ex
defmodule SmokeWeb.MetricsController do
  use SmokeWeb, :controller

  alias Smoke.Server
  alias Smoke.Metrics

  @metrics [
    :counter,
    :sum,
    :last_value,
    :statistics,
    :distribution,
    :max,
    :mean,
    :median,
    :min,
    :mode,
    :p95,
    :p99,
    :variance
  ]

  def list_events(conn, _params) do
    event_names =
      Smoke.Server.list_event_names()
      |> Enum.map(&path_to_strings/1)

    render(conn, event_names: event_names)
  end

  def list_measurements(conn, %{"event_name" => event_name}) do
    measurements =
      event_name
      |> string_to_path()
      |> Smoke.Server.get_events()
      |> Metrics.measurements()
      |> Enum.map(&Atom.to_string/1)

    render(conn, event_name: event_name, measurements: measurements)
  end

  def list_metrics(conn, %{"event_name" => event_name, "measurement" => measurement}) do
    render(conn,
      event_name: event_name,
      measurement: measurement,
      metrics: @metrics
    )
  end

  def list_precisions(conn, %{
        "event_name" => event_name,
        "measurement" => measurement,
        "metric_name" => metric_name
      }) do
    precisions = [:month, :day, :hour, :minute, :second]

    render(conn,
      event_name: event_name,
      measurement: measurement,
      metric_name: metric_name,
      precisions: precisions
    )
  end

  def metrics(conn, %{
        "event_name" => event_name,
        "measurement" => measurement,
        "metric_name" => metric_name,
        "precision" => precision
      }) do
    measurement = String.to_existing_atom(measurement)
    precision = String.to_existing_atom(precision)
    metric_func = metric_function_from_name(metric_name)

    metrics =
      event_name
      |> string_to_path()
      |> Server.get_events()
      |> Metrics.time_bucket(precision)
      |> Metrics.apply_to_bucketed_events(measurement, metric_func)
      |> Enum.map(& &1)

    render(conn,
      metric_name: metric_name,
      event_name: event_name,
      measurement: measurement,
      precision: precision,
      metrics: metrics
    )
  end

  defp metric_function_from_name("counter"), do: &Metrics.counter/2
  defp metric_function_from_name("sum"), do: &Metrics.sum/2
  defp metric_function_from_name("last_value"), do: &Metrics.last_value/2
  defp metric_function_from_name("statistics"), do: &Metrics.statistics/2
  defp metric_function_from_name("distribution"), do: &Metrics.distribution/2
  defp metric_function_from_name("max"), do: &Metrics.max/2
  defp metric_function_from_name("mean"), do: &Metrics.mean/2
  defp metric_function_from_name("median"), do: &Metrics.median/2
  defp metric_function_from_name("min"), do: &Metrics.min/2
  defp metric_function_from_name("mode"), do: &Metrics.mode/2
  defp metric_function_from_name("p95"), do: &Metrics.p95/2
  defp metric_function_from_name("p99"), do: &Metrics.p99/2
  defp metric_function_from_name("variance"), do: &Metrics.variance/2

  defp path_to_strings(path) do
    Enum.join(path, ".")
  end

  defp string_to_path(names) do
    names
    |> String.split(".")
    |> Enum.map(&String.to_existing_atom/1)
  end
end

lib/smoke_web/views/metrics_view.ex
defmodule SmokeWeb.MetricsView do
  use SmokeWeb, :view

  def render("list_events.json", data),
    do: Map.take(data, [:event_names])

  def render("list_measurements.json", data),
    do: Map.take(data, [:event_name, :measurements])

  def render("list_metrics.json", data),
    do: Map.take(data, [:event_name, :measurement, :metrics])

  def render("list_precisions.json", data),
    do: Map.take(data, [:event_name, :measurement, :metric_name, :precisions])

  def render("metrics.json", data),
    do: Map.take(data, [:event_name, :measurement, :metrics, :precision, :metric_name])
end

lib/smoke_web/templates/metrics/aggregate.html.eex
<ul>
    <li><%= @aggregate %></li>
</ul>

lib/smoke_web/templates/metrics/aggregates.html.eex
<ul>
    <%= for {key, value} <- @aggregates do %>
        <li><%= key %>: <%= value %></li>
    <% end %>
</ul>

lib/smoke_web/templates/metrics/index.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3>Tracked Events</h3>
  <ul>
    <%= for event_name <- @event_names do %>
      <li>
        <%= link(event_name, to: Routes.metrics_path(@conn, :measurements, event_name), class: "btn") %>
      </li>
    <% end %>
  </ul>
</div>

lib/smoke_web/templates/metrics/list_events.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3>Tracked Events</h3>
  <ul>
    <%= for event_name <- @event_names do %>
      <li>
        <%= link(event_name, to: Routes.metrics_path(@conn, :list_measurements, event_name), class: "btn") %>
      </li>
    <% end %>
  </ul>
</div>

lib/smoke_web/templates/metrics/list_measurements.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3><%= @event_name %></h3>

  <h4>Measurements</h4>
  <ul>
    <%= for measurement <- @measurements do %>
      <li>
        <%= link(measurement, to: Routes.metrics_path(@conn, :list_metrics, @event_name, measurement), class: "btn") %>
      </li>
    <% end %> 
  </ul>
</div>

lib/smoke_web/templates/metrics/list_metrics.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3><%= @event_name %></h3>
  <h4><%= @measurement %></h4>
  <ul>
    <%= for metric <- @metrics do %>
      <li>        
        <%= link(metric, to: Routes.metrics_path(@conn, :list_precisions, @event_name, @measurement, metric), class: "btn") %>
      </li>
    <% end %> 
  </ul>
</div>

lib/smoke_web/templates/metrics/list_precisions.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3><%= @event_name %></h3>
  <h4><%= @measurement %></h4>
  <h4><%= @event_name %></h4>
  <ul>
    <%= for precision <- @precisions do %>
      <li>        
        <%= link(precision, to: Routes.metrics_path(@conn, :metrics, @event_name, @measurement, @metric_name, precision), class: "btn") %>
      </li>
    <% end %> 
  </ul>
</div>

lib/smoke_web/templates/metrics/measurements.html.eex
<div class="jumbotron">
  <h2>Metrics</h2>
  
  <h3><%= @event_name %></h3>

  <h4>Measurements</h4>
  <ul>
    <%= for measurement <- @measurements do %>
      <li>
        <%= link(measurement, to: Routes.metrics_path(@conn, :metrics, @event_name, measurement), class: "btn") %>
      </li>
    <% end %> 
  </ul>
</div>

lib/smoke_web/templates/metrics/metrics.html.eex
<div class="jumbotron">
  <h2><%= @metric_name %></h2>
  
  <h3><%= @event_name %>.<%= @measurement %></h3>

  <h4>Bucketed by <%= @precision %></h4>

  <ul>
    <%= for %{time: time, metric: metric} <- @metrics do %>
        <li><%= time %>
        <%= case metric do 
            %{} = aggregates -> render("aggregates.html", aggregates: aggregates)
            aggregate -> render("aggregate.html", aggregate: aggregate)
         end %>
         </li>
    <% end %>
  </ul>
</div>